const ROLE = {
  ADMIN: 'ADMIN',
  LIQUIDADOR: 'LIQUIDADOR',
  CLIENT: 'CLIENT',
};

const CATTLE_TYPE = {
  VACA: 'VACA',
  TORO: 'TORO',
  BUFALO: 'BUFALO',
  NOVILLO: 'NOVILLO',
  TERNERO: 'TERNERO',
};

const CATTLE_SEX = {
  MACHO: 'MACHO',
  HEMBRA: 'HEMBRA',
};

const LINK_REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const SHEET_AUDIT_ACTION = {
  PLANILLA_CREATED: 'PLANILLA_CREATED',
  PLANILLA_UPDATED: 'PLANILLA_UPDATED',
  PLANILLA_DELETED: 'PLANILLA_DELETED',
  ROW_ADDED: 'ROW_ADDED',
  ROW_UPDATED: 'ROW_UPDATED',
  ROW_DELETED: 'ROW_DELETED',
  ROW_REORDERED: 'ROW_REORDERED',
  PRICE_CHANGED: 'PRICE_CHANGED',
  PAYMENT_STATUS_CHANGED: 'PAYMENT_STATUS_CHANGED',
  SELLER_CHANGED: 'SELLER_CHANGED',
  BUYER_CHANGED: 'BUYER_CHANGED',
  LIQUIDADOR_ALIAS_CHANGED: 'LIQUIDADOR_ALIAS_CHANGED',
  LINK_REQUEST_APPROVED: 'LINK_REQUEST_APPROVED',
  LINK_REQUEST_REJECTED: 'LINK_REQUEST_REJECTED',
};

const SYSTEM_SETTING_KEYS = {
  DEFAULT_PRICE_PER_HEAD: 'DEFAULT_PRICE_PER_HEAD',
};

module.exports = {
  ROLE,
  CATTLE_TYPE,
  CATTLE_SEX,
  LINK_REQUEST_STATUS,
  SHEET_AUDIT_ACTION,
  SYSTEM_SETTING_KEYS,
};
